<script setup>
import { computed, onMounted, ref } from 'vue'
import { api, perform, state, statusNames, formatDate } from '../api'
import Icon from '../components/Icon.vue'
import Status from '../components/Status.vue'
const items = ref([]), filter = ref(''), loading = ref(true), busy = ref(false), dialog = ref(false), selected = ref(null), action = ref(''), note = ref(''), detail = ref(false)
const role = computed(() => state.user.role)
const filtered = computed(() => items.value.filter(item => !filter.value || item.status === filter.value))
const actionNames = { approve: '批准申请', reject: '驳回申请', onboard: '确认上岗', finish: '确认结束', withdraw: '撤销申请' }
const confirmNames = { approve: '确认批准申请', reject: '确认驳回申请', onboard: '确认上岗', finish: '确认结束', withdraw: '确认撤销申请' }
async function load() { loading.value = true; const result = await perform(() => api('/applications')); if (result) items.value = result.items; loading.value = false }
onMounted(load)
function open(item, act) { selected.value = item; action.value = act; note.value = ''; dialog.value = true }
function show(item) { selected.value = item; detail.value = true }
async function submit() {
  busy.value = true
  const result = await perform(() => api(`/applications/${selected.value.id}/actions`, { method: 'POST', body: { action: action.value, note: note.value } }), `${actionNames[action.value]}成功`)
  if (result) { dialog.value = false; await load() }
  busy.value = false
}
</script>
<template>
  <div><div class="page-heading"><div><p class="section-kicker">EVERY STEP, CLEARLY RECORDED</p><h1>{{ role === 'student' ? '我的申请进度' : role === 'unit' ? '申请审核与流转' : '全校申请总览' }}<span class="heading-dot">.</span></h1><p>{{ role === 'student' ? '从提交到上岗，及时查看每一步的状态。' : '按允许的状态流转处理申请，录用名额与计薪条款同步记录。' }}</p></div><button class="btn btn-secondary" :disabled="loading" @click="load"><Icon name="refresh" :size="17" />刷新</button></div>
    <div class="workflow-strip"><span><i>1</i>提交申请</span><Icon name="chevron" :size="15" /><span><i>2</i>单位批准</span><Icon name="chevron" :size="15" /><span><i>3</i>确认上岗</span><Icon name="chevron" :size="15" /><span><i>4</i>服务结束</span></div>
    <div class="filter-tabs" aria-label="按申请状态筛选"><button :class="{ active: !filter }" @click="filter = ''">全部 <small>{{ items.length }}</small></button><button v-for="s in ['pending_review','approved','onboard','finished','rejected','withdrawn']" :key="s" :class="{ active: filter === s }" @click="filter = s">{{ statusNames[s] }}<small>{{ items.filter(a => a.status === s).length }}</small></button></div>
    <el-skeleton v-if="loading" :rows="7" animated />
    <div v-else class="application-list"><article v-for="item in filtered" :key="item.id" class="application-card" :data-application-id="item.id"><div class="application-main"><span class="unit-mark"><Icon name="briefcase" :size="22" /></span><div class="application-info"><div class="application-title"><button class="title-button" @click="show(item)">{{ item.job_title }}</button><Status :value="item.status" /></div><p>{{ item.unit_name }}<span v-if="role !== 'student'"> · {{ item.student_name }}</span><span> · 第 {{ item.application_no }} 次申请</span></p><small>提交于 {{ formatDate(item.created_at) }}</small></div><div class="application-actions"><button class="btn btn-small btn-secondary" @click="show(item)">详情</button><template v-if="role === 'student' && ['pending_review','approved'].includes(item.status)"><button class="btn btn-small btn-ghost" :disabled="busy" @click="open(item, 'withdraw')">撤销</button></template><template v-if="role === 'unit'"><template v-if="item.status === 'pending_review'"><button class="btn btn-small btn-primary" :disabled="busy || !!item.blocked_reason" @click="open(item, 'approve')">批准</button><button class="btn btn-small btn-ghost" :disabled="busy" @click="open(item, 'reject')">驳回</button></template><button v-if="item.status === 'approved'" class="btn btn-small btn-primary" :disabled="busy" @click="open(item, 'onboard')">确认上岗</button><button v-if="item.status === 'onboard'" class="btn btn-small btn-secondary" :disabled="busy" @click="open(item, 'finish')">确认结束</button></template></div></div><p v-if="role === 'unit' && item.status === 'pending_review' && item.blocked_reason" class="application-note"><Icon name="info" :size="15" />{{ item.blocked_reason }}；待审核申请将保留。</p><p v-if="item.review_note" class="application-note"><Icon name="files" :size="15" />审核说明：{{ item.review_note }}</p><p v-if="item.salary_snapshot" class="frozen-note"><Icon name="shield" :size="14" />计薪已冻结：¥{{ Number(item.salary_snapshot.wage) }} / {{ item.salary_snapshot.category === 'fixed' ? '月基准' : '小时' }}</p></article><div v-if="!filtered.length" class="empty-state panel"><Icon name="files" :size="36" /><h3>还没有这类申请</h3><p>{{ role === 'student' ? '去发现一个适合自己的校园岗位吧。' : '新的申请将在这里展示。' }}</p><router-link v-if="role === 'student'" to="/jobs" class="btn btn-primary">发现岗位</router-link></div></div>
    <el-dialog v-model="dialog" :title="actionNames[action]" width="480px"><form v-if="selected" @submit.prevent="submit"><p class="confirm-title">{{ selected.job_title }} · {{ selected.student_name }}</p><p class="muted">{{ action === 'approve' ? '批准会占用本批次名额，并冻结当前岗位的计薪条款。' : action === 'withdraw' ? '撤销后将释放已批准名额；仅第一次撤销允许再次申请一次。' : action === 'finish' ? '结束后不能新登记工时，但可更正已有记录；本招聘批次名额保留。' : action === 'onboard' ? '确认后可以登记上岗日期及之后的工时。' : '驳回后此学生不可再次申请同一招聘批次，请说明原因。' }}</p><label v-if="action !== 'withdraw'" class="field">{{ action === 'reject' ? '驳回原因（必填）' : '处理说明（选填）' }}<textarea v-model.trim="note" rows="3" :required="action === 'reject'" :minlength="action === 'reject' ? 3 : 0" maxlength="1000"></textarea></label><div class="modal-actions"><button type="button" class="btn btn-secondary" @click="dialog = false">取消</button><button class="btn btn-primary" :disabled="busy">{{ busy ? '处理中…' : confirmNames[action] }}</button></div></form></el-dialog>
    <el-drawer v-model="detail" title="申请记录" size="min(500px, 100%)"><div v-if="selected"><Status :value="selected.status" /><h2>{{ selected.job_title }}</h2><p class="muted">{{ selected.unit_name }} · {{ selected.student_name }} · 第 {{ selected.application_no }} 次申请</p><h3>申请理由</h3><p class="preserve-lines muted">{{ selected.reason }}</p><h3>状态时间线</h3><div class="timeline"><div v-for="[label, value] in [['提交申请', selected.created_at], ['单位批准', selected.approved_at], ['确认上岗', selected.onboard_at], ['确认结束', selected.finished_at], ['本人撤销', selected.withdrawn_at]].filter(([, v]) => v)" :key="label"><i></i><b>{{ label }}</b><span>{{ formatDate(value) }}</span></div></div><h3 v-if="selected.review_note">审核说明</h3><p class="muted">{{ selected.review_note }}</p><div v-if="selected.salary_snapshot" class="notice"><Icon name="shield" /><span>批准时冻结：{{ selected.salary_snapshot.category === 'fixed' ? '固定岗' : '临时岗' }}，¥{{ selected.salary_snapshot.wage }} / {{ selected.salary_snapshot.category === 'fixed' ? '月基准；按40小时折算封顶' : '小时' }}。之后岗位改薪不会覆盖此条款。</span></div><h3>申请时看到的岗位</h3><p class="muted">{{ selected.job_snapshot.location }} · {{ selected.job_snapshot.area }} 区<br>申请时工资：¥{{ selected.job_snapshot.wage }}；批准前可能调整，以批准时冻结条款为准。</p></div></el-drawer>
  </div>
</template>
