<script setup>
import { onMounted, ref } from 'vue'
import { api, perform, formatDate } from '../api'
import Icon from '../components/Icon.vue'
const items = ref([]), loading = ref(true), selected = ref(null), show = ref(false)
const actionNames = { 'demo.seed': '初始化模拟数据', 'student.register': '学生注册', 'student.activate': '启用学生', 'student.hardship_confirm': '确认困难演示等级', 'profile.update': '更新本人档案', 'job.create': '创建岗位草稿', 'job.update': '修改岗位', 'job.publish': '发布岗位', 'job.close': '主动关闭岗位', 'job.delete': '删除岗位草稿', 'job.quota_sync': '名额联动岗位状态', 'application.create': '提交申请', 'application.approve': '批准申请', 'application.reject': '驳回申请', 'application.withdraw': '撤销申请', 'application.onboard': '确认上岗', 'application.finish': '确认结束', 'workhour.create': '登记工时', 'workhour.correct': '追加工时更正', 'workhour.verify': '核实工时有效', 'user.create': '创建管理账号', 'unit.create': '创建单位', 'settings.matching_update': '更新匹配参数', 'policy.import_verified': '导入已核验政策' }
async function load() { loading.value = true; const result = await perform(() => api('/admin/audit?limit=100')); if (result) items.value = result.items; loading.value = false }
onMounted(load)
function view(item) { selected.value = item; show.value = true }
</script>
<template><div><div class="page-heading"><div><p class="section-kicker">A TRACE FOR EVERY KEY ACTION</p><h1>关键操作，有迹可循<span class="heading-dot">.</span></h1><p>成功业务写入同步记录操作者、时间与前后值。审计为应用层追加记录。</p></div><button class="btn btn-secondary" :disabled="loading" @click="load"><Icon name="refresh" :size="17" />刷新记录</button></div><el-skeleton v-if="loading" :rows="8" animated /><section v-else class="panel"><div class="panel-heading"><h3>最近 {{ items.length }} 条记录</h3><span class="mini-label">仅系统管理员可见</span></div><div class="table-scroll"><table><thead><tr><th>时间</th><th>操作者</th><th>关键操作</th><th>关联记录</th><th>详情</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ formatDate(item.created_at) }}</td><td>{{ item.actor }}</td><td>{{ actionNames[item.action] || item.action }}</td><td>{{ item.resource_type }} <span v-if="item.resource_id">#{{ item.resource_id }}</span></td><td><button class="text-button" @click="view(item)"><Icon name="eye" :size="16" />查看前后值</button></td></tr></tbody></table></div></section><el-drawer v-model="show" title="操作审计详情" size="min(620px, 100%)"><div v-if="selected"><span class="section-kicker">AUDIT #{{ selected.id }}</span><h2>{{ actionNames[selected.action] || selected.action }}</h2><p class="muted">{{ selected.actor }} · {{ formatDate(selected.created_at) }}</p><h3>操作前</h3><pre class="json-block">{{ JSON.stringify(selected.before, null, 2) }}</pre><h3>操作后</h3><pre class="json-block">{{ JSON.stringify(selected.after, null, 2) }}</pre></div></el-drawer></div></template>
