<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api, perform, state, today, formatDate } from '../api'
import Icon from '../components/Icon.vue'
const docs = ref([]), question = ref(''), result = ref(null), busy = ref(false), importing = ref(false), saving = ref(false), docDetail = ref(null), docDrawer = ref(false)
const form = reactive({ title: '', publisher: '', source_url: '', version: '', verified_at: `${today()}T00:00`, verification_note: '', is_school_policy: false, text: '' })
async function load() { const data = await perform(() => api('/policies')); if (data) docs.value = data.items }
onMounted(load)
async function search(text = null) { if (typeof text === 'string') question.value = text; if (question.value.trim().length < 2) return; busy.value = true; result.value = await perform(() => api('/qa', { method: 'POST', body: { question: question.value.trim(), conversation_id: 'my-policy-query' } })); busy.value = false }
async function read(doc) { docDetail.value = await perform(() => api(`/policies/${doc.id}`)); if (docDetail.value) docDrawer.value = true }
async function save() {
  saving.value = true
  const sections = form.text.split('\n').map(s => s.trim()).filter(Boolean).map((line, i) => {
    const pos = line.indexOf('|'); return pos > 0 ? { location: line.slice(0, pos).trim(), text: line.slice(pos + 1).trim() } : { location: `原文片段 ${i + 1}`, text: line }
  })
  const { text: _text, ...metadata } = form
  if (await perform(() => api('/policies', { method: 'POST', body: { ...metadata, sections } }), '已核验政策原文已导入')) { importing.value = false; await load() }
  saving.value = false
}
</script>
<template>
  <div><div class="page-heading"><div><p class="section-kicker">ANSWERS BEGIN WITH SOURCES</p><h1>读原文，让了解有依据<span class="heading-dot">.</span></h1><p>检索已核验的政策原文，保留条款位置、来源与版本。</p></div><button v-if="state.user.role === 'aid'" class="btn btn-primary" @click="importing = true"><Icon name="plus" :size="18" />导入已核验原文</button><span v-else class="outline-pill"><Icon name="book" :size="16" />政策原文查询</span></div>
    <div class="policy-layout"><section class="panel policy-main"><div class="policy-intro"><span class="policy-symbol"><Icon name="book" :size="28" /></span><h2>关于勤工助学，<br>从一个关键词开始。</h2><p>查找标题、条款或正文关键词，直接阅读原文片段。</p></div><form class="policy-search" @submit.prevent="search()"><Icon name="search" :size="21" /><input v-model.trim="question" aria-label="政策查询关键词" placeholder="例如：每周、固定岗位、酬金…" required minlength="2" maxlength="500"><button class="btn btn-primary" :disabled="busy">{{ busy ? '查询中…' : '查询原文' }}<Icon name="right" :size="17" /></button></form><div class="query-chips"><span>试着查查</span><button v-for="q in ['每周','每月','固定岗位','酬金']" :key="q" :disabled="busy" @click="search(q)">{{ q }}<Icon name="arrow" :size="13" /></button></div>
      <div v-if="result" class="policy-results" aria-live="polite"><div class="query-result-title"><Icon :name="result.citations.length ? 'check' : 'info'" :size="20" /><b>{{ result.answer }}</b></div><article v-for="(hit, i) in result.citations" :key="`${hit.source.id}-${hit.location}`" class="citation-card"><div><span class="citation-number">{{ String(i + 1).padStart(2,'0') }}</span><span class="mini-label">{{ hit.location }}</span></div><blockquote>{{ hit.text }}</blockquote><div class="citation-source"><b>{{ hit.source.title }}</b><span>{{ hit.source.publisher }} · {{ hit.source.version }}</span><a :href="hit.source.source_url" target="_blank" rel="noopener noreferrer">查看官方来源<Icon name="external" :size="15" /></a></div></article><p class="caption">{{ result.notice }}</p></div><div v-else class="policy-placeholder"><Icon name="shield" :size="21" /><span>每个片段都附出处；没有可靠依据时，会明确提示。<br>学校细则尚未提供，不推测学校规则。</span></div>
    </section><aside class="panel knowledge-panel"><div class="panel-heading"><h3>已收录原文</h3><span class="mini-label">{{ docs.length }} 份</span></div><button v-for="doc in docs" :key="doc.id" class="knowledge-doc" @click="read(doc)"><Icon name="book" :size="23" /><b>{{ doc.title }}</b><span>{{ doc.version }} · {{ doc.section_count }} 段原文</span><small>核验：{{ formatDate(doc.verified_at) }}</small><span class="green-text"><Icon name="shield" :size="14" />已核验来源</span></button><div v-if="!docs.length" class="empty-state"><Icon name="book" :size="30" /><h3>知识库尚未收录已核验原文</h3><p>资助中心取得可靠来源并核验后导入。当前查询会如实提示缺少依据。</p></div><div class="notice neutral"><Icon name="info" /><span>当前为原文查询模式。完整 RAG 与模型岗位助手尚未接入。</span></div></aside></div>
    <el-drawer v-model="docDrawer" title="已核验政策原文" size="min(600px, 100%)"><div v-if="docDetail"><h2>{{ docDetail.title }}</h2><p class="muted">{{ docDetail.publisher }} · {{ docDetail.version }}</p><a class="text-button" :href="docDetail.source_url" target="_blank" rel="noopener noreferrer">打开官方来源<Icon name="external" :size="16" /></a><p class="caption">{{ docDetail.verification_note }}<br>核验时间：{{ formatDate(docDetail.verified_at) }}</p><section v-for="section in docDetail.sections" :key="section.location" class="original-section"><h3>{{ section.location }}</h3><p>{{ section.text }}</p></section></div></el-drawer>
    <el-dialog v-model="importing" title="导入已核验政策原文" width="640px"><form @submit.prevent="save"><div class="notice"><Icon name="shield" /><span>请先核对官方原文及版本。此操作记录为资助中心已完成核验，不会自动验证网址内容。</span></div><label class="field">政策标题<input v-model.trim="form.title" required minlength="2" maxlength="200"></label><div class="form-grid"><label class="field">发布主体<input v-model.trim="form.publisher" required minlength="2" maxlength="100"></label><label class="field">版本<input v-model.trim="form.version" required maxlength="100" placeholder="例如：2018年修订"></label></div><label class="field">实际来源链接<input v-model.trim="form.source_url" type="url" required maxlength="500" placeholder="https://官方发布原文网址"></label><label class="field">已完成核验的时间<input v-model="form.verified_at" type="datetime-local" required></label><label class="field">核验依据和结论<textarea v-model.trim="form.verification_note" required minlength="5" rows="2" maxlength="2000"></textarea></label><label class="field">条款与原文（每行一段，定位 | 原文）<textarea v-model="form.text" rows="6" required placeholder="第二十一条 | 粘贴实际原文；不要填写自行生成的政策内容"></textarea></label><label class="checkbox-label"><input v-model="form.is_school_policy" type="checkbox">这是已核验的本校正式细则</label><div class="modal-actions"><button type="button" class="btn btn-secondary" @click="importing = false">取消</button><button class="btn btn-primary" :disabled="saving">核验完成并导入</button></div></form></el-dialog>
  </div>
</template>
