<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api, perform, state } from '../api'
import Icon from '../components/Icon.vue'
import SlotEditor from '../components/SlotEditor.vue'
const form = reactive({ display_name: '', major: '', skills: [], slots: [], area: 'A' }), busy = ref(false), loading = ref(true)
const skillOptions = computed(() => Object.entries(state.meta?.skills || {}).filter(([key]) => !['s1','s2'].includes(key)))
onMounted(async () => { const result = await perform(() => api('/profiles/me')); if (result) Object.assign(form, { display_name: result.display_name, major: result.major, skills: result.skills || [], slots: (result.slots || []).map(s => ({ ...s })), area: result.area || 'A' }); loading.value = false })
async function save() { busy.value = true; const result = await perform(() => api('/profiles/me', { method: 'PUT', body: form }), '档案已更新，匹配会按最新资料计算'); if (result) state.user = result; busy.value = false }
</script>
<template>
  <div><div class="page-heading"><div><p class="section-kicker">LET OPPORTUNITIES KNOW YOU</p><h1>让机会，更懂你<span class="heading-dot">.</span></h1><p>完善技能和课余时间，为每一次匹配提供可靠依据。</p></div></div><el-skeleton v-if="loading" :rows="6" animated /><form v-else class="profile-layout" @submit.prevent="save"><section class="panel profile-form"><div class="panel-heading"><h3>我的基本资料</h3><Icon name="user" /></div><div class="form-grid"><label class="field">显示姓名<input v-model.trim="form.display_name" required maxlength="50"></label><label class="field">专业与年级<input v-model.trim="form.major" maxlength="100" placeholder="如：计算机科学与技术 · 2024级"></label></div><label class="field">常用区域<select v-model="form.area"><option v-for="(label, key) in state.meta.areas" :key="key" :value="key">{{ label }}</option></select></label><fieldset class="skill-picker"><legend>我的技能（也可明确保存空列表）</legend><label v-for="[key,label] in skillOptions" :key="key"><input v-model="form.skills" type="checkbox" :value="key">{{ label }}</label></fieldset><div class="form-section"><h3>每周可用时段</h3><p class="muted">选择固定的课余时间。相互重叠的时段会合并计算，跨日请分开填写。</p><SlotEditor v-model="form.slots" /></div><div class="modal-actions"><button class="btn btn-primary" :disabled="busy">{{ busy ? '保存中…' : '保存我的档案' }}<Icon name="check" :size="17" /></button></div></section><aside class="panel profile-aside"><span class="section-kicker">YOUR PROFILE AT A GLANCE</span><span class="large-avatar">{{ form.display_name.slice(0, 1) || '我' }}</span><h3>{{ form.display_name || '我的档案' }}</h3><p>{{ form.major || '专业与年级待填写' }}</p><div class="profile-fact"><span>学生账号</span><b>{{ state.user.username }}</b></div><div class="profile-fact"><span>演示困难等级</span><b>{{ state.user.hardship_confirmed ? state.user.hardship : '待确认' }}</b></div><div class="notice"><Icon name="shield" /><span>困难等级由资助中心确认，学生档案不能自行修改。D1 / D2 / D3 为演示代码，不是学校正式认定。</span></div><div class="profile-fact"><span>已选技能</span><b>{{ form.skills.length }} 项</b></div><div class="profile-fact"><span>可用时段</span><b>{{ form.slots.length }} 个</b></div><router-link to="/matching" class="btn btn-secondary full-width"><Icon name="sparkles" :size="17" />查看我的匹配</router-link></aside></form>
  </div>
</template>
