<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api, perform, partNames, formatDate } from '../api'
import Icon from '../components/Icon.vue'
const data = ref(null), weights = reactive({ time: 40, hardship: 25, skills: 25, location: 10 }), busy = ref(false)
const total = computed(() => Object.values(weights).reduce((a, b) => a + b, 0))
const descriptions = { time: '学生可用时段与岗位要求的分钟覆盖比例', hardship: '资助中心已确认的 D1 / D2 / D3 演示映射', skills: '规范化词表中精确命中的技能比例', location: '同区100、相邻70、A/C跨区40' }
onMounted(async () => { data.value = await perform(() => api('/admin/settings')); if (data.value) Object.assign(weights, data.value.weights) })
async function save() { busy.value = true; const result = await perform(() => api('/admin/settings/matching', { method: 'PUT', body: weights }), '匹配参数已保存为新版本'); if (result) data.value = { ...data.value, ...result }; busy.value = false }
</script>
<template><div><div class="page-heading"><div><p class="section-kicker">TRANSPARENT RULES, EXPLAINABLE MATCHES</p><h1>匹配规则，清晰可调<span class="heading-dot">.</span></h1><p>调整四项权重，保存版本记录。已有工资快照不受匹配参数影响。</p></div><span v-if="data" class="outline-pill">当前参数 v{{ data.version }}</span></div><div class="settings-layout"><form class="panel settings-form" @submit.prevent="save"><div class="panel-heading"><h3>四维匹配权重</h3><button type="button" class="text-button" @click="Object.assign(weights, { time: 40, hardship: 25, skills: 25, location: 10 })">填入默认值</button></div><label v-for="(value, key) in weights" :key="key" class="weight-control"><span><b>{{ partNames[key] }}</b><small>{{ descriptions[key] }}</small></span><input v-model.number="weights[key]" type="range" min="0" max="100" step="1" :aria-label="`${partNames[key]}权重`"><div class="weight-number"><input v-model.number="weights[key]" type="number" min="0" max="100" step="1" required :aria-label="`${partNames[key]}权重数值`"><span>%</span></div></label><div class="weight-total" :class="{ invalid: total !== 100 }"><span>权重合计</span><b>{{ total }}%</b><small>{{ total === 100 ? '可以保存' : '四项之和必须为100' }}</small></div><div class="modal-actions"><button class="btn btn-primary" :disabled="busy || total !== 100">{{ busy ? '保存中…' : '保存为新参数版本' }}</button></div></form><aside class="panel settings-explainer"><Icon name="shield" :size="30" /><h3>让每一次调整可解释</h3><p>每项必须为 0–100 的整数，总和为 100。保存会记录参数版本、操作者和时间。</p><p>缺失资料时不把分数填成零；完整资料补齐后，才参与总分排名。</p><div v-if="data" class="profile-fact"><span>最近修改</span><b>{{ formatDate(data.modified_at) }}</b></div><div class="notice neutral"><Icon name="info" /><span>工时上限仍为原型默认周8 / 月40小时；固定岗折算基准为40小时。学校正式规则需取得并核验后再版本化调整。</span></div></aside></div></div></template>
