<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api, perform, state, roleNames } from '../api'
import Icon from '../components/Icon.vue'
import Status from '../components/Status.vue'
const items = ref([]), units = ref([]), keyword = ref(''), loading = ref(true), busy = ref(false), createDialog = ref(false), hardshipDialog = ref(false), selected = ref(null), hardship = ref('D2'), note = ref('')
const form = reactive({ username: '', password: '', display_name: '', role: 'unit', unit_id: null })
const role = computed(() => state.user.role)
const filtered = computed(() => items.value.filter(u => (role.value !== 'aid' || u.role === 'student') && (!keyword.value || `${u.display_name} ${u.username}`.includes(keyword.value))))
async function load() { loading.value = true; await perform(async () => { const [u, n] = await Promise.all([api('/admin/users'), api('/admin/units')]); items.value = u.items; units.value = n.items }); loading.value = false }
onMounted(load)
async function activate(user) { busy.value = true; if (await perform(() => api(`/admin/users/${user.id}/activate`, { method: 'POST' }), '学生已启用，现在可以登录')) await load(); busy.value = false }
function confirmHardship(user) { selected.value = user; hardship.value = user.hardship || 'D2'; note.value = ''; hardshipDialog.value = true }
async function saveHardship() { busy.value = true; if (await perform(() => api(`/admin/users/${selected.value.id}/hardship`, { method: 'POST', body: { hardship: hardship.value, note: note.value } }), '演示困难等级已确认')) { hardshipDialog.value = false; await load() }; busy.value = false }
function create() { Object.assign(form, { username: '', password: '', display_name: '', role: 'unit', unit_id: units.value[0]?.id || null }); createDialog.value = true }
async function saveUser() { busy.value = true; if (await perform(() => api('/admin/users', { method: 'POST', body: { ...form, unit_id: form.role === 'unit' ? Number(form.unit_id) : null } }), '管理账号已创建')) { createDialog.value = false; await load() }; busy.value = false }
</script>
<template>
  <div><div class="page-heading"><div><p class="section-kicker">PEOPLE AT THE CENTER</p><h1>{{ role === 'aid' ? '确认学生困难演示等级' : '让校园服务有序接入' }}<span class="heading-dot">.</span></h1><p>{{ role === 'aid' ? '困难代码仅为原型演示约定，真实认定需以学校核验标准为准。' : '学生注册后待启用；管理角色由管理员创建并明确单位归属。' }}</p></div><button v-if="role === 'admin'" class="btn btn-primary" @click="create"><Icon name="plus" :size="18" />创建管理账号</button></div>
    <div class="notice neutral"><Icon name="shield" /><span>{{ role === 'aid' ? '仅资助中心可确认困难演示等级；等级确认后，学生的匹配困难分才会生效。' : '系统管理员负责启用账号；学生困难等级由资助中心确认。单位管理员只能管理绑定单位。' }}</span></div><div class="filter-bar"><label class="search-field"><Icon name="search" :size="18" /><input v-model.trim="keyword" aria-label="搜索用户" placeholder="搜索显示姓名或账号…"></label><span class="muted">{{ filtered.length }} 个账号</span><button class="btn btn-secondary" :disabled="loading" @click="load"><Icon name="refresh" :size="16" />刷新</button></div>
    <el-skeleton v-if="loading" :rows="6" animated /><section v-else class="panel"><div class="user-list"><article v-for="user in filtered" :key="user.id" class="user-row"><span class="small-avatar" :class="`role-${user.role}`">{{ user.display_name.slice(0, 1) }}</span><div class="row-main"><b>{{ user.display_name }}</b><small>{{ user.username }} · {{ user.unit_name || user.major || roleNames[user.role] }}</small></div><span class="mini-label">{{ roleNames[user.role] }}</span><Status :value="user.status" /><span v-if="user.role === 'student'" class="hardship-label">{{ user.hardship_confirmed ? `${user.hardship} 已确认` : '等级待确认' }}</span><div class="user-actions"><el-popconfirm v-if="role === 'admin' && user.status === 'pending_activation'" title="确认启用此学生账号？" @confirm="activate(user)"><template #reference><button class="btn btn-small btn-primary" :disabled="busy">启用学生</button></template></el-popconfirm><button v-if="role === 'aid' && user.role === 'student'" class="btn btn-small btn-secondary" :disabled="busy" @click="confirmHardship(user)">{{ user.hardship_confirmed ? '更新等级' : '确认等级' }}</button></div></article><div v-if="!filtered.length" class="empty-state">暂无符合条件的账号</div></div></section>
    <el-dialog v-model="hardshipDialog" title="确认困难演示等级" width="460px"><form @submit.prevent="saveHardship"><p class="confirm-title">{{ selected?.display_name }} · {{ selected?.username }}</p><label class="field">演示困难代码<select v-model="hardship"><option value="D1">D1 · 困难分 0</option><option value="D2">D2 · 困难分 50</option><option value="D3">D3 · 困难分 100</option></select></label><label class="field">确认说明<textarea v-model.trim="note" rows="3" required minlength="3" maxlength="1000" placeholder="记录演示确认说明，不使用真实学生信息"></textarea></label><p class="caption">这只是演示代码映射，不是学校正式认定。</p><div class="modal-actions"><button type="button" class="btn btn-secondary" @click="hardshipDialog = false">取消</button><button class="btn btn-primary" :disabled="busy">确认并保存</button></div></form></el-dialog>
    <el-dialog v-model="createDialog" title="创建非学生管理账号" width="500px"><form @submit.prevent="saveUser"><div class="form-grid"><label class="field">账号<input v-model.trim="form.username" required pattern="[a-zA-Z0-9_-]{3,32}" maxlength="32" autocomplete="off"></label><label class="field">显示姓名<input v-model.trim="form.display_name" required maxlength="50"></label></div><label class="field">初始密码<input v-model="form.password" type="password" minlength="8" maxlength="100" required autocomplete="new-password"></label><label class="field">管理角色<select v-model="form.role"><option value="unit">用工单位管理员</option><option value="aid">资助中心工作人员</option><option value="admin">系统管理员</option></select></label><label v-if="form.role === 'unit'" class="field">绑定单位<select v-model="form.unit_id" required><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.name }}</option></select></label><div class="modal-actions"><button type="button" class="btn btn-secondary" @click="createDialog = false">取消</button><button class="btn btn-primary" :disabled="busy">创建账号</button></div></form></el-dialog>
  </div>
</template>
