<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api, perform, state, money, today, formatDate } from '../api'
import Icon from '../components/Icon.vue'
import Status from '../components/Status.vue'
const month = ref('2026-09'), data = ref(null), applications = ref([]), loading = ref(true), busy = ref(false), dialog = ref(false), action = ref('add'), selected = ref(null), history = ref(null), historyDialog = ref(false), onlyPending = ref(false)
const form = reactive({ application_id: null, work_date: today(), hours: 2, reason: '', note: '' })
const role = computed(() => state.user.role)
const rows = computed(() => data.value?.items.filter(row => !onlyPending.value || row.state === 'pending') || [])
const onboard = computed(() => applications.value.filter(a => a.status === 'onboard'))
async function load() { loading.value = true; await perform(async () => { const [d, a] = await Promise.all([api(`/workhours?month=${month.value}`), api('/applications')]); data.value = d; applications.value = a.items }); loading.value = false }
onMounted(load)
function open(mode, row = null) { action.value = mode; selected.value = row; Object.assign(form, { application_id: onboard.value[0]?.id || null, work_date: row?.work_date || today(), hours: row ? Number(row.hours) : 2, reason: '', note: '' }); dialog.value = true }
async function submit() {
  busy.value = true
  const path = action.value === 'add' ? '/workhours' : `/workhours/${selected.value.id}/${action.value === 'correct' ? 'corrections' : 'verify'}`
  const body = action.value === 'verify' ? { note: form.note } : { ...(action.value === 'add' ? { application_id: Number(form.application_id) } : {}), work_date: form.work_date, hours: form.hours, reason: form.reason }
  const result = await perform(() => api(path, { method: 'POST', body }), action.value === 'verify' ? '已核实有效，金额已重新计算' : action.value === 'correct' ? '更正已保存，原记录仍可查看' : '工时已登记')
  if (result) { dialog.value = false; await load() }
  busy.value = false
}
async function viewHistory(row) { const result = await perform(() => api(`/workhours/${row.id}/history`)); if (result) { history.value = result.items; historyDialog.value = true } }
</script>
<template>
  <div><div class="page-heading"><div><p class="section-kicker">YOUR EFFORT, ON THE RECORD</p><h1>{{ role === 'aid' ? '异常工时核实' : '工时有记录，薪酬有依据' }}<span class="heading-dot">.</span></h1><p>{{ role === 'student' ? '查看本人有效工时、待核记录与每月应结算估算。' : '工时更正保留完整历史，正常与待核金额分别计算。' }}</p></div><div class="heading-actions"><label class="month-picker"><Icon name="calendar" :size="17" /><input v-model="month" type="month" aria-label="统计月份" @change="load"></label><button v-if="role === 'unit'" class="btn btn-primary" @click="open('add')"><Icon name="plus" :size="18" />登记工时</button></div></div>
    <el-skeleton v-if="loading" :rows="6" animated />
    <template v-else-if="data"><div class="metrics-grid"><article class="metric-card"><div class="metric-top"><span>正常有效工时</span><Icon name="clock" /></div><p class="metric-value">{{ Number(data.summary.normal_hours) }}<small>小时</small></p><span class="metric-note">含异常已核实记录</span></article><article class="metric-card"><div class="metric-top"><span>异常待核工时</span><Icon name="hourglass" /></div><p class="metric-value warning-color">{{ Number(data.summary.pending_hours) }}<small>小时</small></p><span class="metric-note">整条超限记录待核</span></article><article class="metric-card"><div class="metric-top"><span>正常薪酬估算</span><Icon name="money" /></div><p class="metric-value">{{ money(data.summary.normal_amount) }}<small>元</small></p><span class="metric-note">基于批准时冻结条款</span></article><article class="metric-card"><div class="metric-top"><span>待核薪酬估算</span><Icon name="info" /></div><p class="metric-value warning-color">{{ money(data.summary.pending_amount) }}<small>元</small></p><span class="metric-note">全部待核若确认的金额增量</span></article></div>
      <div class="notice neutral"><Icon name="info" /><span>所选自然月：{{ month }}。应结算估算值，不代表实际发薪。原型默认跨岗位每周 8 / 每月 40 小时，超限整条进入待核；资助中心确认后重新计入。</span></div>
      <section class="panel hours-panel"><div class="panel-heading"><h3>当前有效工时记录 <small class="muted">{{ rows.length }} 条</small></h3><div class="inline-actions"><label class="checkbox-label"><input v-model="onlyPending" type="checkbox">仅看待核实</label><button class="icon-button" aria-label="刷新工时" @click="load"><Icon name="refresh" :size="17" /></button></div></div><div class="hours-records"><article v-for="row in rows" :key="row.id" class="hours-row" :data-hour-id="row.id"><div class="hour-date"><b>{{ row.work_date.slice(8) }}</b><small>{{ row.work_date.slice(0, 7) }}</small></div><div class="row-main"><b>{{ row.job_title }}</b><small>{{ role === 'student' ? row.unit_name : `${row.student_name} · ${row.unit_name}` }}</small><p v-if="row.reason" class="caption">{{ row.reason }}</p></div><span class="hour-value">{{ Number(row.hours) }}<small>小时</small></span><Status :value="row.state" /><div class="hour-actions"><button class="text-button" @click="viewHistory(row)"><Icon name="history" :size="15" />历史</button><button v-if="role === 'unit'" class="text-button" :disabled="busy" @click="open('correct', row)">更正</button><button v-if="role === 'aid' && row.state === 'pending'" class="btn btn-primary btn-small" :disabled="busy" @click="open('verify', row)">核实有效</button></div></article><div v-if="!rows.length" class="empty-state"><Icon name="clock" :size="32" /><h3>该月份暂无符合条件的工时</h3><p>初始演示工时在 2026 年 9 月，可切换月份查看。</p></div></div></section>
      <section v-if="data.summary.groups.length" class="panel payroll-panel"><div class="panel-heading"><h3>按申请汇总的薪酬估算</h3><span class="mini-label">{{ month }} 自然月</span></div><div class="table-scroll"><table><thead><tr><th>岗位 / 同学</th><th>冻结计薪基准</th><th>正常 / 待核工时</th><th>正常估算</th><th>待核增量</th></tr></thead><tbody><tr v-for="group in data.summary.groups" :key="group.application_id"><td><b>{{ group.job_title }}</b><small>{{ group.student_name }}</small></td><td>¥{{ group.salary_snapshot.wage }}<small>{{ group.salary_snapshot.category === 'fixed' ? '固定岗 · 月薪基准，40h折算' : '临时岗 · 每小时' }}</small></td><td>{{ group.normal_hours }} / {{ group.pending_hours }} h</td><td class="amount">¥{{ money(group.normal_amount) }}</td><td class="amount warning-color">¥{{ money(group.pending_amount) }}</td></tr></tbody></table></div></section>
    </template>
    <el-dialog v-model="dialog" :title="action === 'add' ? '登记新工时' : action === 'correct' ? '追加工时更正' : '核实当前记录有效'" width="500px"><form @submit.prevent="submit"><template v-if="action !== 'verify'"><label v-if="action === 'add'" class="field">已上岗申请<select v-model="form.application_id" required><option v-if="!onboard.length" value="">暂无已上岗申请，请先确认上岗</option><option v-for="app in onboard" :key="app.id" :value="app.id">{{ app.student_name }} · {{ app.job_title }}</option></select></label><p v-else class="confirm-title">{{ selected.student_name }} · {{ selected.job_title }}</p><div class="form-grid"><label class="field">工时日期<input v-model="form.work_date" type="date" required :max="today()"></label><label class="field">工时（小时）<input v-model.number="form.hours" type="number" :min="action === 'correct' ? 0 : 0.01" max="24" step="0.01" required></label></div><label class="field">{{ action === 'correct' ? '更正说明（必填）' : '登记说明（选填）' }}<textarea v-model.trim="form.reason" rows="3" :required="action === 'correct'" :minlength="action === 'correct' ? 3 : 0" maxlength="1000"></textarea></label><p class="caption">{{ action === 'correct' ? '更正为0表示作废；旧记录保留，新记录如超限需重新核实。' : '只允许登记上岗后的中国自然日工时；跨日请分条登记。' }}</p></template><template v-else><p class="confirm-title">{{ selected.student_name }} · {{ selected.job_title }}</p><p class="muted">{{ selected.work_date }}，共 {{ selected.hours }} 小时。确认这条超限记录有效后，将从待核转入正常估算，超限标记仍保留。</p><label class="field">核实说明（必填）<textarea v-model.trim="form.note" rows="3" required minlength="3" maxlength="1000" placeholder="说明核实依据；无法确认时请要求单位更正"></textarea></label></template><div class="modal-actions"><button type="button" class="btn btn-secondary" @click="dialog = false">取消</button><button class="btn btn-primary" :disabled="busy || (action === 'add' && !onboard.length)">{{ busy ? '保存中…' : action === 'verify' ? '确认有效并重算' : '保存工时记录' }}</button></div></form></el-dialog>
    <el-dialog v-model="historyDialog" title="原始记录与更正链" width="600px"><div class="history-list"><article v-for="(row, i) in history" :key="row.id"><div><span class="mini-label">{{ i === 0 ? '原始记录' : '追加更正' }} #{{ row.id }}</span><Status :value="row.state" /></div><h3>{{ row.work_date }} · {{ row.hours }} 小时</h3><p>{{ row.reason || '无附加说明' }}</p><p v-if="row.verification_note">核实说明：{{ row.verification_note }}</p><small class="muted">{{ row.operator_name }} · {{ formatDate(row.created_at) }}</small><p v-if="i === history.length - 1" class="caption green-text">当前链尾参与累计，之前记录仅留作历史。</p></article></div></el-dialog>
  </div>
</template>
